"use client";
import {useEffect,useState} from "react";
const URL="https://xqdsmbyealtammgmpsqe.supabase.co",KEY="sb_publishable_78q5LVudkA7u2hqsecLmAw_br2XlkUB",SESSION="airealsolutions.factory.session.v1";
type Account={user_id:string;email:string;created_at:string;last_sign_in_at:string|null;credits:number};
export default function AdminAccounts(){
 const[accounts,setAccounts]=useState<Account[]>([]),[amount,setAmount]=useState<Record<string,string>>({}),[reason,setReason]=useState<Record<string,string>>({}),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 useEffect(()=>{void load()},[]);
 function token(){try{return JSON.parse(localStorage.getItem(SESSION)||"{}").access_token||""}catch{return""}}
 async function rpc(name:string,body:object={}){const t=token();if(!t){location.href="/login";throw new Error("Sign in required")}const r=await fetch(URL+"/rest/v1/rpc/"+name,{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||"Admin request failed");return d}
 async function load(){try{const d=await rpc("factory_admin_accounts");setAccounts(Array.isArray(d)?d:[])}catch(e){setMsg(e instanceof Error?e.message:"Admin access required")}}
 async function grant(a:Account){const n=Number(amount[a.user_id]);if(!Number.isInteger(n)||n<=0){setMsg("Enter a positive whole number of credits.");return}setBusy(a.user_id);try{const bal=await rpc("factory_admin_grant_credits",{target_user:a.user_id,amount:n,reason:reason[a.user_id]||"Manual admin credit"});setMsg("Credits added. New balance: "+Number(bal).toLocaleString());setAmount(v=>({...v,[a.user_id]:""}));await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not grant credits")}finally{setBusy("")}}
 return <section style={{maxWidth:1200,margin:"0 auto",padding:"64px 24px"}}><span className="product-tag">Owner administration</span><h1>Accounts & Credits</h1><p>Track Factory accounts and issue promotional, incentive, testing, or courtesy credits. Every grant is recorded in the append-only credit ledger.</p>{msg&&<p>{msg}</p>}<div style={{display:"grid",gap:16,marginTop:28}}>{accounts.map(a=><article key={a.user_id} style={{padding:22,border:"1px solid #d9d9d9",borderRadius:16}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><strong>{a.email}</strong><p>Joined {new Date(a.created_at).toLocaleDateString()} · Last sign in {a.last_sign_in_at?new Date(a.last_sign_in_at).toLocaleString():"Never"}</p></div><div><small>Credit balance</small><h2>{Number(a.credits||0).toLocaleString()}</h2></div></div><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><label>Credits<br/><input type="number" min="1" step="1" value={amount[a.user_id]||""} onChange={e=>setAmount(v=>({...v,[a.user_id]:e.target.value}))}/></label><label>Reason<br/><input value={reason[a.user_id]||""} placeholder="Welcome incentive" onChange={e=>setReason(v=>({...v,[a.user_id]:e.target.value}))}/></label><button className="button button-primary" disabled={busy===a.user_id} onClick={()=>void grant(a)}>{busy===a.user_id?"Adding…":"Add Credits"}</button></div></article>)}</div></section>
}
