"use client";
import {useEffect,useMemo,useState} from "react";
const URL="https://xqdsmbyealtammgmpsqe.supabase.co",KEY="sb_publishable_78q5LVudkA7u2hqsecLmAw_br2XlkUB",SESSION="airealsolutions.factory.session.v1";
type Account={user_id:string;email:string;created_at:string;last_sign_in_at:string|null;credits:number;account_status:string;referral_source:string|null;admin_notes:string|null;credits_granted:number;credits_used:number};
type Incentive={id:string;code:string;name:string;description:string|null;credit_amount:number;active:boolean;program_type:string}; type Promo={id:string;code:string;description:string|null;credit_amount:number;max_redemptions:number|null;redemption_count:number;active:boolean};
export default function AdminAccounts(){
 const[accounts,setAccounts]=useState<Account[]>([]),[programs,setPrograms]=useState<Incentive[]>([]),[promos,setPromos]=useState<Promo[]>([]),[amount,setAmount]=useState<Record<string,string>>({}),[reason,setReason]=useState<Record<string,string>>({}),[search,setSearch]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 useEffect(()=>{void load()},[]);
 function token(){try{return JSON.parse(localStorage.getItem(SESSION)||"{}").access_token||""}catch{return""}}
 async function rpc(name:string,body:object={}){const t=token();if(!t){location.href="/login";throw new Error("Sign in required")}const r=await fetch(URL+"/rest/v1/rpc/"+name,{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||"Admin request failed");return d}
 async function load(){try{const[a,p,pc]=await Promise.all([rpc("factory_admin_accounts"),rpc("factory_admin_incentives"),rpc("factory_admin_promos")]);setAccounts(Array.isArray(a)?a:[]);setPrograms(Array.isArray(p)?p:[]);setPromos(Array.isArray(pc)?pc:[])}catch(e){setMsg(e instanceof Error?e.message:"Admin access required")}}
 async function grant(a:Account,preset?:number,label?:string){const n=preset||Number(amount[a.user_id]);if(!Number.isInteger(n)||n<=0){setMsg("Enter a positive whole number of credits.");return}setBusy(a.user_id);try{const bal=await rpc("factory_admin_grant_credits",{target_user:a.user_id,amount:n,reason:label||reason[a.user_id]||"Manual admin credit"});setMsg(n.toLocaleString()+" credits added to "+a.email+". New balance: "+Number(bal).toLocaleString());setAmount(v=>({...v,[a.user_id]:""}));await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not grant credits")}finally{setBusy("")}}
 async function status(a:Account,new_status:string){setBusy(a.user_id);try{await rpc("factory_admin_update_account",{target_user:a.user_id,new_status,source:a.referral_source||"",notes:a.admin_notes||""});setMsg(a.email+" updated to "+new_status+".");await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not update account")}finally{setBusy("")}}
 async function saveProgram(p:Incentive,credit_amount:number,active:boolean){setBusy(p.id);try{await rpc("factory_admin_set_incentive",{program_code:p.code,credit_amount,is_active:active});setMsg(p.name+" updated.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not update incentive")}finally{setBusy("")}}
 async function createPromo(){const code=prompt("Promotion code (example: LAUNCH5000)");if(!code)return;const credits=Number(prompt("Credits to grant","5000"));if(!Number.isInteger(credits)||credits<=0)return setMsg("Enter a valid credit amount.");const maxRaw=prompt("Maximum redemptions (leave blank for unlimited)","");const max=maxRaw?Number(maxRaw):null;try{await rpc("factory_admin_create_promo",{p_code:code,p_description:"Factory promotion",p_credits:credits,p_max:max});setMsg("Promotion code created.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Could not create promotion")}}
 const shown=useMemo(()=>accounts.filter(a=>a.email.toLowerCase().includes(search.toLowerCase())),[accounts,search]);
 const totals=useMemo(()=>({accounts:accounts.length,balance:accounts.reduce((s,a)=>s+Number(a.credits||0),0),granted:accounts.reduce((s,a)=>s+Number(a.credits_granted||0),0),used:accounts.reduce((s,a)=>s+Number(a.credits_used||0),0)}),[accounts]);
 return <section style={{maxWidth:1200,margin:"0 auto",padding:"64px 24px"}}><span className="product-tag">Owner administration</span><h1>Customer Administration</h1><p>Manage Factory accounts, promotional incentives and manual credits. Credit grants remain in the ledger for auditability.</p>{msg&&<p><strong>{msg}</strong></p>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,margin:"28px 0"}}><Metric n={totals.accounts} label="Accounts"/><Metric n={totals.balance} label="Outstanding credits"/><Metric n={totals.granted} label="Credits granted"/><Metric n={totals.used} label="Credits consumed"/></div>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,flexWrap:"wrap"}}><div><h2>Promotion codes</h2><p>Create redeemable codes for launch campaigns, referrals, demos and customer incentives.</p></div><button className="button button-primary" onClick={()=>void createPromo()}>+ Create Promo Code</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14,marginBottom:36}}>{promos.map(p=><article key={p.id} style={card}><span className="product-tag">{p.active?"Active":"Off"}</span><h3>{p.code}</h3><p>{Number(p.credit_amount).toLocaleString()} credits</p><small>{p.redemption_count} redeemed{p.max_redemptions!==null?` / ${p.max_redemptions} max`:" · unlimited"}</small></article>)}</div>
 <h2>Incentive programs</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14,marginBottom:36}}>{programs.map(p=><article key={p.id} style={card}><span className="product-tag">{p.program_type}</span><h3>{p.name}</h3><p>{p.description}</p><p><strong>{Number(p.credit_amount).toLocaleString()} credits</strong> · {p.active?"Active":"Off"}</p><div style={row}><button className="button" disabled={busy===p.id} onClick={()=>void saveProgram(p,p.credit_amount,!p.active)}>{p.active?"Turn Off":"Turn On"}</button><button className="button" onClick={()=>{const n=prompt("Credit amount",String(p.credit_amount));if(n&&Number(n)>0)void saveProgram(p,Number(n),p.active)}}>Change Amount</button></div></article>)}</div>
 <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"end",flexWrap:"wrap"}}><div><h2>Accounts</h2><p>Search, grant credits, or change customer status.</p></div><label>Search accounts<br/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Email address"/></label></div>
 <div style={{display:"grid",gap:16,marginTop:18}}>{shown.map(a=><article key={a.user_id} style={card}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><strong>{a.email}</strong><p>Joined {new Date(a.created_at).toLocaleDateString()} · Last sign in {a.last_sign_in_at?new Date(a.last_sign_in_at).toLocaleString():"Never"}</p><p>Status: <strong>{a.account_status}</strong></p></div><div><small>Available</small><h2>{Number(a.credits||0).toLocaleString()}</h2><small>{Number(a.credits_granted||0).toLocaleString()} granted · {Number(a.credits_used||0).toLocaleString()} consumed</small></div></div>
 <div style={row}><label>Credits<br/><input type="number" min="1" step="1" value={amount[a.user_id]||""} onChange={e=>setAmount(v=>({...v,[a.user_id]:e.target.value}))}/></label><label>Reason<br/><input value={reason[a.user_id]||""} placeholder="Courtesy / promotion" onChange={e=>setReason(v=>({...v,[a.user_id]:e.target.value}))}/></label><button className="button button-primary" disabled={busy===a.user_id} onClick={()=>void grant(a)}>{busy===a.user_id?"Working…":"Add Credits"}</button>{programs.filter(p=>p.active).map(p=><button key={p.id} className="button" disabled={busy===a.user_id} onClick={()=>void grant(a,Number(p.credit_amount),p.name)}>{p.name}</button>)}</div>
 <div style={{...row,marginTop:12}}><small>Account controls:</small>{["active","beta","suspended","internal"].map(s=><button key={s} className="button" disabled={busy===a.user_id||a.account_status===s} onClick={()=>void status(a,s)}>{s}</button>)}</div></article>)}</div></section>
}
const card={padding:22,border:"1px solid #d9d9d9",borderRadius:16} as const,row={display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"} as const;
function Metric({n,label}:{n:number,label:string}){return <article style={card}><small>{label}</small><h2>{Number(n||0).toLocaleString()}</h2></article>}
