"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./EconomicsPanel.module.css";

const SUPABASE_URL="https://xqdsmbyealtammgmpsqe.supabase.co";
const SUPABASE_KEY="sb_publishable_78q5LVudkA7u2hqsecLmAw_br2XlkUB";
const empty={pricing_model:"undecided",discovery_revenue:0,implementation_revenue:0,monthly_recurring_revenue:0,other_monthly_revenue:0,estimated_build_cost:0,actual_build_cost:0,monthly_infrastructure_cost:0,monthly_ai_api_cost:0,monthly_support_cost:0,customer_acquisition_cost:0,target_customer_monthly_price:0,target_setup_price:0,target_customers:0,customer_value_monthly:0,hours_saved_monthly:0,economic_status:"evaluate",revenue_notes:"",graduation_notes:""};
type Economics=typeof empty;
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v||0)}
function num(v:string){const n=Number(v);return Number.isFinite(n)?n:0}

export default function EconomicsPanel({projectSlug}:{projectSlug:string}){
 const [projectId,setProjectId]=useState(""); const [form,setForm]=useState<Economics>(empty); const [signedIn,setSignedIn]=useState(false); const [status,setStatus]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{void load()},[projectSlug]);
 async function auth(){const raw=localStorage.getItem("airealsolutions.factory.auth.v1"); if(!raw)return null; try{const x=JSON.parse(raw); return x?.access_token||null}catch{return null}}
 async function load(){const token=await auth(); setSignedIn(!!token); if(!token)return; const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`}; const p=await fetch(`${SUPABASE_URL}/rest/v1/factory_projects?slug=eq.${encodeURIComponent(projectSlug)}&select=id&limit=1`,{headers}); if(!p.ok)return; const rows=await p.json(); const id=rows?.[0]?.id; if(!id)return; setProjectId(id); const r=await fetch(`${SUPABASE_URL}/rest/v1/factory_project_economics?project_id=eq.${id}&select=*`,{headers}); if(r.ok){const e=await r.json(); if(e?.[0])setForm({...empty,...e[0]});}}
 const monthlyRevenue=form.monthly_recurring_revenue+form.other_monthly_revenue+(form.target_customer_monthly_price*form.target_customers);
 const monthlyCost=form.monthly_infrastructure_cost+form.monthly_ai_api_cost+form.monthly_support_cost;
 const monthlyMargin=monthlyRevenue-monthlyCost;
 const upfrontRevenue=form.discovery_revenue+form.implementation_revenue+(form.target_setup_price*form.target_customers);
 const investment=Math.max(form.actual_build_cost||form.estimated_build_cost,0)+form.customer_acquisition_cost;
 const netLaunch=upfrontRevenue-investment;
 const breakEvenMonths=monthlyMargin>0?Math.max(0,-netLaunch/monthlyMargin):null;
 const grossMargin=monthlyRevenue>0?((monthlyRevenue-monthlyCost)/monthlyRevenue)*100:0;
 const recommendation=useMemo(()=>{if(monthlyRevenue>0&&grossMargin>=60&&netLaunch>=0)return "SELL / SCALE"; if(monthlyMargin>0&&breakEvenMonths!==null&&breakEvenMonths<=12)return "BUILD / SELL"; if(form.customer_value_monthly>0&&form.target_customer_monthly_price>form.customer_value_monthly*.5)return "REPRICE"; if(investment>0&&monthlyMargin<=0)return "PAUSE / REWORK ECONOMICS"; return "VALIDATE WHO PAYS"},[monthlyRevenue,grossMargin,netLaunch,monthlyMargin,breakEvenMonths,form.customer_value_monthly,form.target_customer_monthly_price,investment]);
 function set<K extends keyof Economics>(k:K,v:Economics[K]){setForm(f=>({...f,[k]:v}))}
 async function save(){const token=await auth(); if(!token||!projectId){setStatus("Sign in to save economics.");return} setSaving(true);setStatus(""); const payload={...form,project_id:projectId,updated_at:new Date().toISOString()}; const r=await fetch(`${SUPABASE_URL}/rest/v1/factory_project_economics?on_conflict=project_id`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)}); setSaving(false); setStatus(r.ok?"Economics saved to the Factory.":`Save failed: ${await r.text()}`)}
 const field=(label:string,key:keyof Economics,prefix="$"|""="$")=><label><span>{label}</span><div className={styles.inputWrap}>{prefix&&<b>{prefix}</b>}<input type="number" min="0" step="any" value={form[key] as number} onChange={e=>set(key,num(e.target.value) as never)}/></div></label>;
 return <section className={styles.panel} id="economics"><div className={styles.head}><div><span className="product-tag">Economics gate</span><h2>Who pays, when do we get paid, and is it worth building?</h2><p>Every Factory project carries its own revenue, cost, margin and break-even model. Estimates can start rough and become actuals as the product matures.</p></div><div className={styles.actions}><button onClick={save} disabled={!signedIn||saving}>{saving?"Saving…":"Save economics"}</button></div></div>
 {!signedIn&&<div className={styles.notice}>Sign in through the Factory build flow to edit and save private economics. The calculations below remain available for planning.</div>}
 <div className={styles.score}><article><small>Upfront revenue</small><strong>{money(upfrontRevenue)}</strong></article><article><small>Monthly revenue</small><strong>{money(monthlyRevenue)}</strong></article><article><small>Monthly operating cost</small><strong>{money(monthlyCost)}</strong></article><article><small>Gross margin</small><strong>{grossMargin.toFixed(0)}%</strong></article><article><small>Break-even</small><strong>{breakEvenMonths===null?"Not yet":`${breakEvenMonths.toFixed(1)} mo`}</strong></article><article className={styles.recommend}><small>Factory decision</small><strong>{recommendation}</strong></article></div>
 <div className={styles.grid}><div className={styles.card}><h3>1. Get paid early</h3>{field("Paid discovery / assessment","discovery_revenue")}{field("Implementation / setup revenue","implementation_revenue")}{field("Target setup price per customer","target_setup_price")}</div><div className={styles.card}><h3>2. Recurring revenue</h3>{field("Existing monthly recurring revenue","monthly_recurring_revenue")}{field("Other monthly revenue","other_monthly_revenue")}{field("Target monthly price per customer","target_customer_monthly_price")}{field("Target paying customers","target_customers","")}</div><div className={styles.card}><h3>3. Investment</h3>{field("Estimated build cost","estimated_build_cost")}{field("Actual build cost","actual_build_cost")}{field("Customer acquisition cost","customer_acquisition_cost")}</div><div className={styles.card}><h3>4. Monthly cost to operate</h3>{field("Infrastructure","monthly_infrastructure_cost")}{field("AI / API usage","monthly_ai_api_cost")}{field("Support / maintenance","monthly_support_cost")}</div><div className={styles.card}><h3>5. Customer value</h3>{field("Value created per customer / month","customer_value_monthly")}{field("Hours saved per customer / month","hours_saved_monthly","")}<label><span>Pricing model</span><select value={form.pricing_model} onChange={e=>set("pricing_model",e.target.value)}><option value="undecided">Undecided</option><option value="project">Project fee</option><option value="subscription">Subscription</option><option value="setup_plus_subscription">Setup + subscription</option><option value="managed_service">Managed service</option><option value="usage">Usage based</option><option value="lead_value">Lead / transaction value</option></select></label></div><div className={styles.card}><h3>6. Capital decision</h3><label><span>Portfolio status</span><select value={form.economic_status} onChange={e=>set("economic_status",e.target.value)}><option value="evaluate">Evaluate</option><option value="sell_now">Sell now</option><option value="build">Build</option><option value="incubate">Incubate</option><option value="maintain">Maintain</option><option value="pause">Pause</option><option value="graduate">Graduate</option></select></label><label><span>Revenue notes</span><textarea value={form.revenue_notes} onChange={e=>set("revenue_notes",e.target.value)} placeholder="Who pays? What pain or outcome justifies the price?"/></label><label><span>Graduation rule</span><textarea value={form.graduation_notes} onChange={e=>set("graduation_notes",e.target.value)} placeholder="What revenue, usage, security or customer milestone justifies dedicated infrastructure?"/></label></div></div>
 <div className={styles.rule}><strong>Factory economic rule</strong><span>Do not graduate infrastructure or expand scope merely because we can build it. Require a customer, measurable internal value, validated demand, or a deliberate strategic investment.</span></div>{status&&<p className={styles.status}>{status}</p>}
 </section>
}